### ISSUE TITLE
Thoughts and suggestions

### ISSUE THREAD

**Issue by km-Poonacha** [Appymp/Vanilla-Analysis#1]
Hey Aps, looks great. And seems like a lot of effort has gone into it. I definitely feel it can be considered for your statement. 

I just had two suggestions for the future incase you have not thought of it -

1) Start the introduction with a research statement (what you are searching for) or problem statement (what problem you want to solve). And at the end write down some implications of your study - what have you learnt that addresses your research and problem statement. 
2) I feel a good way to expand this study is to create regression models estimating  "Success rate of pollination". That is, can you figure out which parameters or which combination of parameters promotes pollination (e.g. may be that some locations tit may be suitable to pollinate on certain days). I think you are trying to do it using your visualizations, but after a point it is better to move to statistical approaches and let the models give you the result.

**Comment by Appymp** [comment]
Thanks Poonacha Anna. Success rate of pollination is a tricky thing to estimate. It would be interesting to see if I could use some regression/machine learning model to estimate it. Since the sample size is small, I assumed that the models might not be too effective. 
 I haven't read any research papers yet so I am not too familiar with the typical format. Do you think the "background" essay is relevant in such a paper? Or is it better to include that separately and start instead with the intro problem statement. The implications of the study sounds like a good way to tie everything together.

**Comment by km-Poonacha** [comment]
1) I would start with an "Introduction Section" which includes the background in very brief. The background would ideally provide a motivation for the problem statement. That is, it would tell why your research in important and  why we need to care about it (maybe it is something unknown or the context is so unique that any previous knowledge is not directly applicable there). So at the end of the introduction you could say  - given this background, i plan to address  [... problem statement/ research question..] through this research. 
2) Following the intro, you could have a "Background" section that details the background. Put everything you have in the background essay there.
3) Then you would have a "Methods" section that describes how you went about addressing the problem. 
4) And finally an "Analysis and Discussion" section where you provide the analysis and findings. At the end of the discussion section, it is good add a subsection -"Implications" which would generalize the findings and highlight what other planters may learn from your research. 

This is how  I would structure the project report. But tell me again, do you need to provide the whole report, or a summary of the project in your statement ?

**Comment by Appymp** [comment]
That sounds like a comprehensive structure! I'll go about making the changes .
For the applications, there is no compulsory requirement for research papers. But technical publications or evidence of intellectual curiosity in the area of the program(data science in my case), serves as one of the considerations. In my personal statement i feel it should be a broader motivation as to why i want to do this course. Within that ill have to slip these projects in, to demonstrate my interest in the subject.

**Comment by km-Poonacha** [comment]
Ok cool! best of luck. Issue closed :-) !
